spring:
  profiles:
    active: dev

api-info:
  base-package: com.iris
  # 标题
  title: 系统设置sdk
  # 描述
  description: system
  # 负责人
  name: RubyWong
  # url
  url: http://XX.XX.XX.XX:XXXX/
  # 负责人邮箱
  email: wangxh@yk.com
  # 版本
  version: 1.0.0-SNAPSHOT

mybatis-plus:
  global-config:
    db-config:
      # 全局字段策略
      #      NOT_NULL：默认策略，非NULL判断（判断传参为null时，不会更新该字段）
      #      IGNORED：忽略判断（不去判断传参是否是null，如果传入null，就更新该字段值为null）
      #      NOT_EMPTY：非空判断（如果传入的参数是“”空字符串或者null，不会插入数据库）
      insert-strategy: not_empty
      update-strategy: not_empty

      # 逻辑删除默认值
      logic-delete-value: 1
      logic-not-delete-value: 0

      # 主键类型
      id-type: assign_uuid